#include "../main.h"
#include <stdio.h>


void foo (char *bar, ...)
{
	va_list va;
	char *str;

	va_start(va, bar);
	str = va_arg(va, char *);
	write(1, str, _strlen(str));
	str = va_arg(va, char *);
	write(1, str, _strlen(str));
}
int main ()
{
	/* Testing raw character input and the output value */
	char s1[] = "Alhamdullilah once and forever\n", s2[] = "", s3[] = "AlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdul\n",
	s4[] = "AlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdul\n\n",
	s5[] = "AlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillah\n",
	s6[] = "AlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdul\n\nAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdul\n",
	s7[] = "AlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamduli\n\nAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdul\n",
	s8[] = "AlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamduli\n\nAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdulillahAlhamdul\n\n";
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(s1), printf(s1));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(s2), printf(s2));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(s3), printf(s3));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(s4), printf(s4));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(s5), printf(s5));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(s6), printf(s6));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(s7), printf(s7));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(s8), printf(s8));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf(NULL), printf(NULL));

	/* Testing passing %n with (int *) argument */
	char buffer[100];
	int i;
    int count;
    int len = snprintf(buffer, sizeof(buffer), "Hello, world!%22n", &count);
    printf("Output: %s\n", buffer);
    printf("The number of characters written so far is %d.\n", count);
    printf("Number of characters written: %d\n", len);
	printf("original printf:\t");
	printf("1111111%n\n", &i);
	printf("i = %d\n", i);
	printf("my printf:\t");
	_printf("1111111%n\n", &i);
	printf("i = %d\n", i);

	/* Testing passing %c and %s */

	char sx1[] = "Alhamdullilah";

	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf("Hi, %c\nBye\n", 'A'), printf("Hi, %c\nBye\n", 'A'));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf("Hi, %s\nBye\n", sx1), printf("Hi, %s\nBye\n", sx1));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf("Hi, %s\nBye\n", NULL), printf("Hi, %s\nBye\n", NULL));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf("Hi, %sAy%s\nBye\n", "1", "YA ALLAH"), printf("Hi, %sAy%s\nBye\n", "2", "YA ALLAH"));
	printf("my printf:\t%d\noriginal printf:\t%d\n", _printf("Hi, %s%s\nBye\n", NULL, "YA ALLAH"), printf("Hi, %s%s\nBye\n", NULL, "YA ALLAH"));
	foo("",  "Bismillah", "Alhamdulillah");
}